apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1   # 1 = we just need 1 DB #
  template:
    metadata:
      labels:
        app: vprodb
    spec:      # specification for pod #
      containers:
      - name: vprodb
        image: vprofile/vprofiledb
        imagePullPolicy: IfNotPresent
        args:
         - "--ignore-db-dir=lost+found"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vpro-db-data
        ports:
        - name: vprodb-port
          containerPort: 3306
        env:               # fetch dbname and pass from env var app-secret.yml file #
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: db-pass
      nodeSelector:         # DB running same zone with the volume created before #
        zone: ap-southeast-2a
      volumes:
        - name: vpro-db-data
          # This AWS EBS volume must already exist and running same zone with db #
          awsElasticBlockStore:
             volumeID: vol-0e2de0d7b82364cd0
             fsType: ext4

