version: '3'
services:
  vprodb:
    image: vprofile/vprofiledb:v1
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
    restart: always

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
    restart: always

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always

  vproapp:
    image: vprofile/vprofileapp:v1
    ports:
      - "8080:8080"
    volumes: 
      - vproappdata:/usr/local/tomcat/webapps
    restart: always

  vproweb:
    image: vprofile/vprofileweb:v1
    ports:
      - "80:80"
    restart: always

volumes:
  vprodbdata: {}
  vproappdata: {}

